---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: minecraft-bedrock
spec:
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: minecraft-bedrock
      namespace: minecraft-bedrock
  interval: 1h
  path: ./kubernetes/apps/minecraft-bedrock/minecraft-bedrock/app
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: minecraft-bedrock
