apiVersion: v1
kind: Secret
metadata:
  name: truenas-csi-secret
  namespace: truenas-csi
stringData:
  api-key: ENC[AES256_GCM,data:qo5VGMnRtrf0JwfW4oQ+VCPId+3w3MtYQJSZX6fXUNSbCEsuh5Ait4aOZAcud8W+Zk4AUYaYLM2FlzkFokv+SfiH,iv:Ze6zxjJQOZXzzdazmXfeyX+w+JIKNetjemZidHggcYk=,tag:p5/mNP0rO9m6s/tADkEycA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBWkxhTzdvdTFpdTB6ZWlU
        TllhTmtYKzhjby9FcGFjOGxQRTE1eHZHSURZCkdUS3lOVUp4a3ZuMi9VRm9ieldM
        c0hPY2VCUW9ZSzJPUmw0L2hSekp5UjgKLS0tIEd0RFBOTzREY0tvbDdwcmlDcVB4
        Q3MwWk9uejZmQURsSWN6RzlZQ1hxVDAKD6Kq6seYGUAEQnDvnNvMAkGQlCLyK4p2
        /lP5hIaJTBChJCyUudSK8m8WTJsKIZWCzStkPPkCWPgTBQ4pcCddTw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1hfvm6lyqshj2mexy0mpw9kj3kj64k75vc6zgwe597djszzyzxd0sdaephm
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-21T09:17:17Z"
  mac: ENC[AES256_GCM,data:C+tRusUVny4zHlGQfij5qsyVZ6DsbAkWoyKeRhJplSicyFittu8YcgIPn1o/5f86+dbuw0MfuQQzPin4lcR6g+9faOitwWHvZrl9f9ZNeHCIAixuuVlcsxRr8Bdp1Rax6z41s/9Szzpi0IHMawFzzxn3m09R9WJ4mb2BqeVgITM=,iv:nCpQ1mhm4iI/vG5gvxw1/1NcL1nql6D6mbuwoJIT350=,tag:LKPFKt/HB/7ZGXzhD3L+uQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
