apiVersion: v1
kind: Secret
metadata:
  name: truenas-csi-secret
  namespace: truenas-csi
stringData:
  api-key: ENC[AES256_GCM,data:gq0sLhzvC73anVO3Xqckua6u6ITBEF1pCGqhQbMAo1qa2yk75PDdxEqxMKsULs/gR39zNeZV8Wuyb9cASHSYsbZT,iv:cwCydFXL0VS9LrnZmmlBE4rc7R3IvWhlWrSYKP5yYsg=,tag:hyNymQKx2k6EU6tHf5IKfw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEejdrS3ArZHNLcWY4YS9a
        ZS9RWU1YVFo3bzBvaXU3L0haRXR4UlhrUTJ3Ckk1VTFZUHA2eGtpSEZaQXhtVEky
        QmdpUXlxWVN1QmNDTkJScE05Si8vZE0KLS0tIGJrUlBNRko4TmxEMFFGWXdLL2pu
        dlJlU29EbitmdlRyWDJaMXpZSm5NY2sK6CJTdErOvUcSEyjGryVIP7wpIz7UgETk
        whzmn/YG8AHPyD1xODlf3EnF8xsHojEJN/oSfUFB88Id0PD1ioD/ew==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1hfvm6lyqshj2mexy0mpw9kj3kj64k75vc6zgwe597djszzyzxd0sdaephm
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-20T12:50:00Z"
  mac: ENC[AES256_GCM,data:eMbMcuDVq1lfANMhSIqJy808QkWYNRdYckZKk9sQ2CXijagZ7dsWmOmRNhGL+jHYsPmc9TUPlxDnpXwhTELwwJGMpEE9tpewsE6+Kc+Exfv8kzscZLQzgDj5VcxizdLXbxYZk3SA9F0WuSlqcbrJv0EPKLuDeJMV3soI6/8Wmuk=,iv:LN/TseTFlQSzWaVvagkjOmS3mwyeRDsi3R/zq3wcvzE=,tag:uAN1IThDb4nxPnA0c2dY2g==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
