apiVersion: v1
kind: Secret
metadata:
  name: truenas-csi-secret
  namespace: truenas-csi
stringData:
  api-key: ENC[AES256_GCM,data:ExrSlo1edL/sLehH1QnV5pkK0TPvO8UkxgGtiiubxPor6911WzLyu2GE/WwzT3Ri8mc5tww193zvDbTaX2qMoyX7,iv:QyTrFzGnY3ocyFq/SEiXvaxePyZHpOVL6R+nvkCexyg=,tag:Utwn0sSi25oa1mI3cjGhzg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpYkVzYlhLZGR4a1ptcnJH
        Zm1VUTI4ZWwxd0FIVkdmTXFLanJoQlZnR3dJCnY4RXd2dWQ0am1NNXdrL3FoeVdV
        c1o0M2FjN09OSW13QjN1UFZFM292ZWcKLS0tIDdIMDNxRXRjZUhDcmkrMzlDSmFD
        ZmxYR0ZXUktqRCtIMUptaVQ3VDRjblEKga5q1Y89iRZCFMOIwI9ycMqywVkmanzV
        TZAoMZ72ZlK6kBkjL9sIHUqa+kcsQHIyMGYR048lmCgyrglT/qs90Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1hfvm6lyqshj2mexy0mpw9kj3kj64k75vc6zgwe597djszzyzxd0sdaephm
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-21T09:39:43Z"
  mac: ENC[AES256_GCM,data:r6nxYvjmXMNyA5cdO0XqVMNdhyATneXmKqXkSEAeM9R09XZWj2RuKMN8Rc4BH6d4dTNbwFFm4O5laXyZqSMo9IjWyL8PsaHGFhOF50mSU4++4non+45lvyywF+B3hNni4RDtzutjtXdSAm42lagjz3ejEXeVK05rBsCWKB/31Os=,iv:/PL1BPps3MnCAw/INT7cm/AjHIVTn3PnY2DP1cqEEQc=,tag:fMSe49JJrGGcTLY22BQx1A==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
