---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: jellyfin
spec:
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: jellyfin
      namespace: jellyfin
  interval: 1h
  path: ./kubernetes/apps/jellyfin/jellyfin/app
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: jellyfin
