apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
  namespace:
stringData:
  placeholder: ENC[AES256_GCM,data:YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBITEJZTG1id2ZOcStqOWVaa01SWEdhUC9xS3hqZUVOQUhwaFJvRUw3N2o0ClJFMHhQZ1VjLzUrMEhsUUw0akxUbXgxMHRQNW1UQ0Z6S1ZVcExCc3NEcEUKLS0tIGs3SFlaMGZtU2FtVXF5UVRienBvWEFpUzM2VnpIRVoxRU53cWR5THU2VVUKURJyvNdalFdSUfYheHUg17paB/U3i0MXEYKvxQQz0aQNAwQ48uUfCydhyUQ=,iv:YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA=,tag:SExCWUxtYndmTnErajllWmtNUlhHYVAvcUt4amVFTkFIcGhSb0VMNzdqNApSRTB4UGdVYy81KzBIbFFMNGpMVG14MTB0UDVtVENGektWVXBMQnNzRHBFCi0tLSBrN0hZWjBmbVNhbVVxeVFUYnpwb1hBaVMzNlZ6SEVaMUVOd3FkeUx1NlVVClEScrzXWpRXUlH2IXh1INe6Wgf1N4tDFxGCr8UEM9GkDQMEOPLlHwsnYclE,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBITEJZTG1id2ZOcStqOWVaa01SWEdhUC9xS3hqZUVOQUhwaFJvRUw3N2o0ClJFMHhQZ1VjLzUrMEhsUUw0akxUbXgxMHRQNW1UQ0Z6S1ZVcExCc3NEcEUKLS0tIGs3SFlaMGZtU2FtVXF5UVRienBvWEFpUzM2VnpIRVoxRU53cWR5THU2VVUKURJyvNdalFdSUfYheHUg17paB/U3i0MXEYKvxQQz0aQNAwQ48uUfCydhyUQ=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1g775pykvu6rhjuvmwqnwejpn689r0ral8e8amsthjv08f0mp69rqy4h7zn
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-19T20:50:00Z"
  mac_only_encrypted: true
  version: 3.13.3
