apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:Yu2ImavuU/ZsbdjOwTKZ7UMc0nr5c+uV9U3nQrBJ+4PkTpbI6bsizm25K3iC32ZeL+BwjTE=,iv:LcZovob9lu52acFrvm2OTSlnAzpEufggYy/PvdJUrAo=,tag:jyX0YNuU2W8pvRweXkc3uQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOTElMdHlqVTI4RE04K2dL
        MzRGazVMdVpjcFRGNGlCMVhIcGVKT1F4SkFvCnJNaXQwTXpnRkY2dGx6SXNtM0VQ
        YThUZmJUN0lYTmZVVUZqdTQzcURPMGsKLS0tIFhuRFd2cFQ3bmxsNnlMZVRiam9z
        Z0diUm9LN1pTQkxVWFZUamdCQ25hOEEK2BZFhcWkc8P3uu5XfN+NoUDF2r5Dtzaj
        UUhedjPVBmqPMNQtxlFTN2c61QJmXMGqB0XtDrF3ORGR4qWYnv/RhQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1hfvm6lyqshj2mexy0mpw9kj3kj64k75vc6zgwe597djszzyzxd0sdaephm
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-16T17:13:33Z"
  mac: ENC[AES256_GCM,data:yzdwlzJp/UtRdgvqIn4X8nSZShAY1yKhjRVtBz19YhOeU3QVbuzJpuqT9Jk4Z0bMs5Ul6Z5P1HDux6zWpaVT3U7L2/8uw+NOIsNd1legvcY46T062derysml2eB1PHSx6i147FMps9eFTzUrC/Ua4jCRp1eRJ1tv7RnGnhASqPo=,iv:j9xY3bI5lZVbiVrLdOGNW//hA7Vuzlu8HORsZG97mU8=,tag:TcVP4ohHNzzJ/Ncq98IUMw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
