apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:3W8JYFyXx9GE9Pe8wJDJ9G8P,iv:dLl01N864Aw8Y9jkuG70yuQigSvhjHxMog+dintBK9c=,tag:NtQT8xsUffV5WtosnVDabw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsREZsRXNtb0Q5NEhnWDcz
        cnROclQrWlNqY2FoZFZBSUxiTGF3R3M5ZGhrCkdMY0RKaUlqdWpHQjZRM090NGNW
        eG01T0xvT1g4VEdJWllUT2FOellOTmsKLS0tIFlMZUdKUmcveE44Slc0SlNndVNa
        eTJ3b0lYajRVSGVaUzB1NWpZOEd4RzAKuZHKCD7W01msBbmsoU3O0B/twulLTER/
        Mz/y9s9HA/FeNDxJvgw29MolrN9S8+9WKp1LrrAUWXDbHbmgwpKrOg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1hfvm6lyqshj2mexy0mpw9kj3kj64k75vc6zgwe597djszzyzxd0sdaephm
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-19T21:09:42Z"
  mac: ENC[AES256_GCM,data:WfLzylAKthqGDOpc/c1fGscL1SQfkRJ1mxVk6gWZejkqGKft5J6x0SM2u/WqRdmuKUQKMEZXiBIyIn+jGKiH8Ppatr/yW7JdwqliZ8+LRiufdEhvQ/pkmatIIVcTFXABt24OAeNCBKNXaw2jl9BIaJ/h3FvEpjmFdoTiRfHHJLg=,iv:IWE74zjyeffnuWshMoXMjB7Fxt+37ALhv1apBRoRTOg=,tag:GhWMiqw9nYJXu36G0jr+sw==,type:str]
  version: 3.13.3
