apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:ZM8BsUTETAqtV8lPqRHVY9NI,iv:PS9LJa6dqniHNP+1XWOqBzdT8JuzeSK6snRhGlCWRZ8=,tag:skQEbY+2I9l5xXjbv8flbQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwSVVpU0Urd0Fwd3FjRzhl
        a2VzQTZwRDRNaWlJUVZhZzBUdkdvbmNTL3pvCnJwc0hrZEFGS0ZoeStSbE53TkNS
        MzlBam1jK2g4SkpiTCtjSkVHc3lDT0EKLS0tIHY2cktXQnZBemZ1SmZDWTNQVzE3
        ejBFNktDaW5rRWRjSlh4eGN2Rmo0SncKG3cGjsuWdfndtvQe894s9pwnwlrAzfQR
        IltwlRD5pIc29gV30UYAtXzKM2haHzfvND5o913cC5F+9VreL5AOxA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1g775pykvu6rhjuvmwqnwejpn689r0ral8e8amsthjv08f0mp69rqy4h7zn
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-19T20:50:43Z"
  mac: ENC[AES256_GCM,data:BjsYIPpUdz6zCLOnBQNOjnlIC8s/mnK6V02/aD+MKX7QBB1cN/EDFg0lVyMHcOI0RtRPnEt60JbWtFifq0DeDcjruKsvzFdAp3ZvdCEGk972gQMU/BRpsQFgz1PwPyQz/YiPI0RqaVgKfAc22faBZA4ZQkE3Ru4DlfmjDpVwIDU=,iv:6LuecnqwhXLuG2pL6ITZzPimBXiMRQVJcCceJRw5uho=,tag:P1VP0RLlH3h4EuY8Csfw/g==,type:str]
  version: 3.13.3
