apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:3b4SacUVAhl9y88ker3EPsJm,iv:xN4FfvroLezpfxm9KUtj4AfJUAEUiooe+9G2iA8zkhU=,tag:xeOOiwwLTnwHVAMbjtXX6w==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArRjlndXQ3czRTMUlPSEE2
        Slo3VWgwZWkrVmdqWE9hTUFCQlR5cjJkK0NFCkpJRFVoY0Q0RnVBbkdaWWxONGIw
        Qk5PZHNEbnhqRy9Ya1JKR2o1THVlbkUKLS0tIHcyTWVwclV4Sk1uUDh2MUd4SFVJ
        M3cxUlE0cCtjZWpJRlEzMHp0OHViVkUKFIEH6m/a7+NOdDMwXg61IovCtnTcwd0+
        f5zBStr+aSFCJImOhpJ+XSJbleAoU43qd5tZvw/KG/Zj9H1pvOgbCA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1hfvm6lyqshj2mexy0mpw9kj3kj64k75vc6zgwe597djszzyzxd0sdaephm
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-19T21:03:02Z"
  mac: ENC[AES256_GCM,data:5huhL7vf2zuRwQiey7NTZQYcm1pqEs/swRwWgR0x2gVNqwA4s5yCQRdgX8n9jHoN+V4bgG6VZkF/Sxv3C9lXCANruVdPsbPDCIy3335eldqTWVw4l5ToVc9+NGx02zEuU8i3VzYxjcIbEJSBKoYOMTEUvwPQcOxSXm09LtcbBvM=,iv:yZW5jywjN9a3dk9fzJGAqtO6LSA0wHBmwqXdsmIAj10=,tag:i/Gmn200xNc7VVrDewr2Lw==,type:str]
  version: 3.13.3
