apiVersion: v1
kind: Secret
metadata:
  name: flux-webhook-token
stringData:
  token: ENC[AES256_GCM,data:ad65spV78RLVhxyUZZwu1nxuQe3KGQr2ismm7BC/u6M=,iv:dMLyqJ4JZO70L/cbAD5CFV+eNnsBc6dVlxBfxKAlmxo=,tag:TvNChwGmkcmqUwIR0VQ/mg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmTWp2UGcycGRTcmZSTjgr
        MDhsRGxFTDZqTFZqYWJKT041WlhkY3h2MkRNCkxmQnhSNXNoblJOQUI5R2R1RnF3
        ZlZnQThQOTQvbFA5enRaWmc4ZGU4RzAKLS0tIDNBVmF5MDUzclhqcGh6aTJqQ2FU
        ckhnblRVc2ViRFErMjFjYUtCWjFrOWsKEybHTnO93FCL2DCdEeLcJWqcMnIQQT+y
        aJTDltt8Tueic/UistEO7/baF1umYI7NgCtnnfQK79Y5EDHH2lw2FQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1hfvm6lyqshj2mexy0mpw9kj3kj64k75vc6zgwe597djszzyzxd0sdaephm
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-16T17:13:33Z"
  mac: ENC[AES256_GCM,data:YKUHwn8PSSS6pml8mN/eSB5+i75DmvN/rxndL1Xt6UOxZFsiNh7sTyZHJhZC0ohJNMsO3RyS65O4CLA7CBYDaYucx0yDQe/9W/fZHLBKKCPex8Po80ASvLqpd9sLTZAOk3nVQ5bZwBPtRATXteJODByczd1MWJ5eeS90BBnulfg=,iv:XkDop5g871RAtOTVk6HmEupkTvlC0Gh3btnEaE0gnhg=,tag:+WIoPpD5AHcLIUv0cZTLcQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
