apiVersion: v1
kind: Secret
metadata:
  name: flux-webhook-token
  namespace:
stringData:
  placeholder: ENC[AES256_GCM,data:YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5eVFPUjAwQ0V6NldOdXd1dXdvNFZSTUpiRXRGR0tiVjVIanc3NjJ5VmxBCjE1QVc0VllWUXMwbEs4NmYwUmFqclRYek9oVTljdGFaUndkcFlXbE5zejgKLS0tIGJzNVcwT0Z5RTNZUHRQa1BqR2k3MU1NMmJmOGhUMlVKYlJQM2FHUjRNaGMKQKV6bOZW+mbxEcLGUpKA3DcYwOcZ0SCDLjk2jqX64wfHmiMSQONUOxemxuc=,iv:YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA=,tag:eXlRT1IwMENFejZXTnV3dXV3bzRWUk1KYkV0RkdLYlY1SGp3NzYyeVZsQQoxNUFXNFZZVlFzMGxLODZmMFJhanJUWHpPaFU5Y3RhWlJ3ZHBZV2xOc3o4Ci0tLSBiczVXME9GeUUzWVB0UGtQakdpNzFNTTJiZjhoVDJVSmJSUDNhR1I0TWhjCkClemzmVvpm8RHCxlKSgNw3GMDnGdEggy45No6l+uMHx5ojEkDjVDsXpsbn,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5eVFPUjAwQ0V6NldOdXd1dXdvNFZSTUpiRXRGR0tiVjVIanc3NjJ5VmxBCjE1QVc0VllWUXMwbEs4NmYwUmFqclRYek9oVTljdGFaUndkcFlXbE5zejgKLS0tIGJzNVcwT0Z5RTNZUHRQa1BqR2k3MU1NMmJmOGhUMlVKYlJQM2FHUjRNaGMKQKV6bOZW+mbxEcLGUpKA3DcYwOcZ0SCDLjk2jqX64wfHmiMSQONUOxemxuc=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1g775pykvu6rhjuvmwqnwejpn689r0ral8e8amsthjv08f0mp69rqy4h7zn
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-19T20:50:00Z"
  mac_only_encrypted: true
  version: 3.13.3
