---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./pvc-cache.yaml
  - ./pvc-data.yaml
  - ./pvc-podcasts.yaml
  - ./pvc-media.yaml
  - ./deployment.yaml
  - ./service.yaml
  - ./httproute.yaml
