---
# Dynamic PVC for Metube downloads (NFS for shared access)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: metube-downloads
  namespace: metube
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: truenas-nfs
  resources:
    requests:
      storage: 100Gi
