---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jackett
  namespace: jackett
  labels:
    app: jackett
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: jackett
  template:
    metadata:
      labels:
        app: jackett
    spec:
      restartPolicy: Always
      containers:
        - name: jackett
          image: linuxserver/jackett:amd64-0.24.2663
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9117
              name: http
          env:
            - name: PUID
              value: "0"
            - name: PGID
              value: "0"
            - name: TZ
              value: "Europe/Malta"
          volumeMounts:
            - name: config
              mountPath: /config
          resources:
            requests:
              memory: 256Mi
              cpu: 100m
            limits:
              memory: 512Mi
              cpu: 250m
          startupProbe:
            tcpSocket:
              port: http
            failureThreshold: 600
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 5
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 5
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: jackett-config
