---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: netshoot
  namespace: troubleshooting
  labels:
    app: netshoot
spec:
  selector:
    matchLabels:
      app: netshoot
  template:
    metadata:
      labels:
        app: netshoot
    spec:
      containers:
        - name: netshoot
          image: docker.io/nicolaka/netshoot:latest
          command: ["sleep", "infinity"]
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 128Mi
      tolerations:
        - operator: Exists
      terminationGracePeriodSeconds: 5
