apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
  namespace:
stringData:
  placeholder: ENC[AES256_GCM,data:YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArWVZtbmRDSXZzdjRKTEE5N2dXT04yZjE5MXVmdlRKVWl5UlNHbzdzOHpzCkZMbUdYNmVRVHp5SFVLQTd1UC9pbGUzNVpwd25OMTZvam9IUk9hN2twSk0KLS0tIDFQUFd0T3I5WFpBMlp0UW15VUlRVEZXRityOFBKSHNveHV5Ykt4MmxaRW8K919CzBZqfuo2fmachiEjw7TR9g4Bgg8abOy+X6uKTaITPQWPN13NVLPY8CA=,iv:YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA=,tag:K1lWbW5kQ0l2c3Y0SkxBOTdnV09OMmYxOTF1ZnZUSlVpeVJTR283czh6cwpGTG1HWDZlUVR6eUhVS0E3dVAvaWxlMzVacHduTjE2b2pvSFJPYTdrcEpNCi0tLSAxUFBXdE9yOVhaQTJadFFteVVJUVRGV0YrcjhQSkhzb3h1eWJLeDJsWkVvCvdfQswWan7qNn5mnIYhI8O00fYOAYIPGmzsvl+rik2iEz0FjzddzVSz2PAg,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArWVZtbmRDSXZzdjRKTEE5N2dXT04yZjE5MXVmdlRKVWl5UlNHbzdzOHpzCkZMbUdYNmVRVHp5SFVLQTd1UC9pbGUzNVpwd25OMTZvam9IUk9hN2twSk0KLS0tIDFQUFd0T3I5WFpBMlp0UW15VUlRVEZXRityOFBKSHNveHV5Ykt4MmxaRW8K919CzBZqfuo2fmachiEjw7TR9g4Bgg8abOy+X6uKTaITPQWPN13NVLPY8CA=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1g775pykvu6rhjuvmwqnwejpn689r0ral8e8amsthjv08f0mp69rqy4h7zn
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-19T20:50:00Z"
  mac_only_encrypted: true
  version: 3.13.3
