apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:+NPrTGdd70JRN0sOqwFCNfMzJYtpgJRsPfBa8/Dv4Ko+fM1b9CRBO2NwL4lteYtQct3onO0tUQoExEa50dUI/xhDeT0hg+j2wPjjSnPv6lah21k6Ng1FyoZdxwJW1AIL8xBresE7eWBUvUqYN9iCNBK9pln5U/6P7nWOKvVWP/9NRi0m+iidEacGaMK2Z59ObTYDeb82VSB2g5xJEUGkyTOPyW7F61x2WDE2Wn2JDgNKDPT9,iv:EodCwvf7/DR+wst0Ye4Dkpn+2nsBxX3Lu4VShXlvH/w=,tag:dj1yvJZWOVWLISeHJ+SPyA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwcWw3ZFg0RC9xU00rc0Js
        RlJ4dFV0UWFxRzRMVVNobURDWnpka1ZnZUVzCnVoMTRJV0xFYWN4UmNZcC8xTzZC
        UjRnVnNFY3hib0UzRjlDS29ubS9FeTQKLS0tIGZaMUN6MnhUSC9Vd01IUW5Zbk1s
        a3k4VFFub0JCTndOeDBGZFJGN1FXRzQKCMfP7WaRYXsszXKT50fk5ej18SMtjNCs
        E0TxQ6FrxADJo6OkM3/hDePVQXsK1Q01ys9aw6VjOe9uudYnNT7SdQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1hfvm6lyqshj2mexy0mpw9kj3kj64k75vc6zgwe597djszzyzxd0sdaephm
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-16T17:13:33Z"
  mac: ENC[AES256_GCM,data:fTc4dLngcL72msRsGd8fZVxhxRdtpLrYl45AaW/tICZK7RPlk3ejE8cLB2F4pminn8DH5z5BfB+qraSoVAswynE35Ozhkr8vCfGPCrowpG2Rh+JSz03sy7fm0BE+gaQPBUD32PwYsM/k5X5VWOeAYs23dOIyliuRi1UZie+lRVQ=,iv:Ee/hHuLwrAnI+NGtPLB5xrBRq0qYEVz/LGfTxeqakNU=,tag:iN50U84ZESTZRscEf1vBrA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
