---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: firefly-iii
spec:
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: firefly-iii
      namespace: firefly-iii
  interval: 1h
  path: ./kubernetes/apps/firefly-iii/firefly-iii/app
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: firefly-iii
