---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cryptofolio
spec:
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: cryptofolio
      namespace: cryptofolio
  interval: 1h
  path: ./kubernetes/apps/cryptofolio/cryptofolio/app
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: cryptofolio
