---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: truenas-csi

components:
  - ../../components/sops

resources:
  - ./namespace.yaml
  - ./truenas-csi/ks.yaml
  - ./storage-classes/ks.yaml
