apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
  namespace:
stringData:
  placeholder: ENC[AES256_GCM,data:YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuY1FjL3d3QlR5dExwMXRQM0Zvek9lWEJzMnRqTlhGdHFCRytXQzRRRGxnCk1ldzFNOEhwcDJ2b0xoTGdrME5FQmhpbjFqYlVPeGQ0cWZ5cGR0WWNoMDAKLS0tIFV6THBSQTVjaUF3T0RGQzkvTitqL20ycW1ZWG5RbmorK2VPM0E2N3g2VmsKsWC0U/hXU2qLNhoV8YEIOdF1xxhrxk8IZE/QPyYxfUoH6ZmAyiwgIZ7eR0I=,iv:YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA=,tag:bmNRYy93d0JUeXRMcDF0UDNGb3pPZVhCczJ0ak5YRnRxQkcrV0M0UURsZwpNZXcxTThIcHAydm9MaExnazBORUJoaW4xamJVT3hkNHFmeXBkdFljaDAwCi0tLSBVekxwUkE1Y2lBd09ERkM5L04rai9tMnFtWVhuUW5qKytlTzNBNjd4NlZrCrFgtFP4V1NqizYaFfGBCDnRdccYa8ZPCGRP0D8mMX1KB+mZgMosICGe3kdC,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuY1FjL3d3QlR5dExwMXRQM0Zvek9lWEJzMnRqTlhGdHFCRytXQzRRRGxnCk1ldzFNOEhwcDJ2b0xoTGdrME5FQmhpbjFqYlVPeGQ0cWZ5cGR0WWNoMDAKLS0tIFV6THBSQTVjaUF3T0RGQzkvTitqL20ycW1ZWG5RbmorK2VPM0E2N3g2VmsKsWC0U/hXU2qLNhoV8YEIOdF1xxhrxk8IZE/QPyYxfUoH6ZmAyiwgIZ7eR0I=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1g775pykvu6rhjuvmwqnwejpn689r0ral8e8amsthjv08f0mp69rqy4h7zn
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-19T20:50:00Z"
  mac_only_encrypted: true
  version: 3.13.3
