apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:jcoYIr2gA5m7ELl3IkwtN9OI+QyQVrw/5PwphBU3z7W89Ro79ZHHpFMLNtL3Zn/n/DYuLvo=,iv:OiOjDAMYoaGyDoWiACeaPCdmspQ2gQ9biPrYIOO+8k8=,tag:jSyPgzQw50sJlffOgd/b/g==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXRVBiVStkbjlpSUxscmJo
        N3hlaFY5d0ZLNVVFNldGb3BvaTRnRGl0V1VZClBiNmMrYUxSRzM2SUdCN0xZRUNn
        UUVDOXA3bEw5b1pYVy9hbGFHVkhvQkUKLS0tIGtraktnWDZJbC9XM2ZZWTI5RmZk
        ejVJUzBZZlIwZDVUME80Qm0wcW52QjQKNJPQui9bN87rQbo989jCtIb5got+4zd1
        QrmniUa1wwS7CwsmSpqPXPqFSTpeIJpVNlVZilBnLKN8ypQAbeNphg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1hfvm6lyqshj2mexy0mpw9kj3kj64k75vc6zgwe597djszzyzxd0sdaephm
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-16T17:13:33Z"
  mac: ENC[AES256_GCM,data:9BTr+hLo3Op0XwWWpBq1deMaaM/9aliB4EcKuJz/oeGYKaL2XD2LRfGQvw80AXJG6fAc+uGEnYcMw5GPPQIlmXyRym9O9PqVXTHzmVQX2ewYA+0mRT5LoyFR5/ftwbWVi13o8hPFvW3SrKIKiaSjgYO/RsB5aH56Ly0Q5xxW0zc=,iv:G6NJqjEoczLurt2e31KLYzEVMZUm7/u4zQje3xSX0q0=,tag:5vel94/PnUm1oW5T72kMDQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
