---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home-assistant-hacs
components:
  - ../../components/sops
resources:
  - ./namespace.yaml
  - ./home-assistant-hacs/ks.yaml
