---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: whisper
spec:
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: whisper
      namespace: whisper
  interval: 1h
  path: ./kubernetes/apps/whisper/whisper/app
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: whisper
