---
apiVersion: v1
kind: Service
metadata:
  name: headlamp
  namespace: headlamp
  labels:
    app: headlamp
spec:
  type: ClusterIP
  selector:
    app: headlamp
  ports:
    - name: https
      port: 80
      targetPort: https
      protocol: TCP
