---
apiVersion: v1
kind: Service
metadata:
  name: whisper
  namespace: whisper
  labels:
    app: whisper
spec:
  type: ClusterIP
  selector:
    app: whisper
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
